# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lucas/workspace/algo2_tp3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lucas/workspace/algo2_tp3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/workspace/algo2_tp3/CMakeFiles /home/lucas/workspace/algo2_tp3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/workspace/algo2_tp3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f CMakeFiles/gtest_main.dir/build.make CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named correrTests

# Build rule for target.
correrTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 correrTests
.PHONY : correrTests

# fast build rule for target.
correrTests/fast:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/build
.PHONY : correrTests/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f CMakeFiles/gtest.dir/build.make CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named correrTests-Wall

# Build rule for target.
correrTests-Wall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 correrTests-Wall
.PHONY : correrTests-Wall

# fast build rule for target.
correrTests-Wall/fast:
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/build
.PHONY : correrTests-Wall/fast

#=============================================================================
# Target rules for targets named correrValgrind

# Build rule for target.
correrValgrind: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 correrValgrind
.PHONY : correrValgrind

# fast build rule for target.
correrValgrind/fast:
	$(MAKE) -f CMakeFiles/correrValgrind.dir/build.make CMakeFiles/correrValgrind.dir/build
.PHONY : correrValgrind/fast

src/BaseDeDatos.o: src/BaseDeDatos.cpp.o

.PHONY : src/BaseDeDatos.o

# target to build an object file
src/BaseDeDatos.cpp.o:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/BaseDeDatos.cpp.o
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/src/BaseDeDatos.cpp.o
.PHONY : src/BaseDeDatos.cpp.o

src/BaseDeDatos.i: src/BaseDeDatos.cpp.i

.PHONY : src/BaseDeDatos.i

# target to preprocess a source file
src/BaseDeDatos.cpp.i:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/BaseDeDatos.cpp.i
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/src/BaseDeDatos.cpp.i
.PHONY : src/BaseDeDatos.cpp.i

src/BaseDeDatos.s: src/BaseDeDatos.cpp.s

.PHONY : src/BaseDeDatos.s

# target to generate assembly for a file
src/BaseDeDatos.cpp.s:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/BaseDeDatos.cpp.s
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/src/BaseDeDatos.cpp.s
.PHONY : src/BaseDeDatos.cpp.s

src/Consulta.o: src/Consulta.cpp.o

.PHONY : src/Consulta.o

# target to build an object file
src/Consulta.cpp.o:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Consulta.cpp.o
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/src/Consulta.cpp.o
.PHONY : src/Consulta.cpp.o

src/Consulta.i: src/Consulta.cpp.i

.PHONY : src/Consulta.i

# target to preprocess a source file
src/Consulta.cpp.i:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Consulta.cpp.i
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/src/Consulta.cpp.i
.PHONY : src/Consulta.cpp.i

src/Consulta.s: src/Consulta.cpp.s

.PHONY : src/Consulta.s

# target to generate assembly for a file
src/Consulta.cpp.s:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Consulta.cpp.s
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/src/Consulta.cpp.s
.PHONY : src/Consulta.cpp.s

src/Driver.o: src/Driver.cpp.o

.PHONY : src/Driver.o

# target to build an object file
src/Driver.cpp.o:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Driver.cpp.o
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/src/Driver.cpp.o
.PHONY : src/Driver.cpp.o

src/Driver.i: src/Driver.cpp.i

.PHONY : src/Driver.i

# target to preprocess a source file
src/Driver.cpp.i:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Driver.cpp.i
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/src/Driver.cpp.i
.PHONY : src/Driver.cpp.i

src/Driver.s: src/Driver.cpp.s

.PHONY : src/Driver.s

# target to generate assembly for a file
src/Driver.cpp.s:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Driver.cpp.s
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/src/Driver.cpp.s
.PHONY : src/Driver.cpp.s

src/Registro.o: src/Registro.cpp.o

.PHONY : src/Registro.o

# target to build an object file
src/Registro.cpp.o:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Registro.cpp.o
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/src/Registro.cpp.o
.PHONY : src/Registro.cpp.o

src/Registro.i: src/Registro.cpp.i

.PHONY : src/Registro.i

# target to preprocess a source file
src/Registro.cpp.i:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Registro.cpp.i
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/src/Registro.cpp.i
.PHONY : src/Registro.cpp.i

src/Registro.s: src/Registro.cpp.s

.PHONY : src/Registro.s

# target to generate assembly for a file
src/Registro.cpp.s:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Registro.cpp.s
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/src/Registro.cpp.s
.PHONY : src/Registro.cpp.s

src/Table.o: src/Table.cpp.o

.PHONY : src/Table.o

# target to build an object file
src/Table.cpp.o:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Table.cpp.o
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/src/Table.cpp.o
.PHONY : src/Table.cpp.o

src/Table.i: src/Table.cpp.i

.PHONY : src/Table.i

# target to preprocess a source file
src/Table.cpp.i:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Table.cpp.i
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/src/Table.cpp.i
.PHONY : src/Table.cpp.i

src/Table.s: src/Table.cpp.s

.PHONY : src/Table.s

# target to generate assembly for a file
src/Table.cpp.s:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/src/Table.cpp.s
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/src/Table.cpp.s
.PHONY : src/Table.cpp.s

tests/driver_test.o: tests/driver_test.cpp.o

.PHONY : tests/driver_test.o

# target to build an object file
tests/driver_test.cpp.o:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/tests/driver_test.cpp.o
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/tests/driver_test.cpp.o
.PHONY : tests/driver_test.cpp.o

tests/driver_test.i: tests/driver_test.cpp.i

.PHONY : tests/driver_test.i

# target to preprocess a source file
tests/driver_test.cpp.i:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/tests/driver_test.cpp.i
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/tests/driver_test.cpp.i
.PHONY : tests/driver_test.cpp.i

tests/driver_test.s: tests/driver_test.cpp.s

.PHONY : tests/driver_test.s

# target to generate assembly for a file
tests/driver_test.cpp.s:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/tests/driver_test.cpp.s
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/tests/driver_test.cpp.s
.PHONY : tests/driver_test.cpp.s

tests/gtest-1.8.1/gtest-all.o: tests/gtest-1.8.1/gtest-all.cc.o

.PHONY : tests/gtest-1.8.1/gtest-all.o

# target to build an object file
tests/gtest-1.8.1/gtest-all.cc.o:
	$(MAKE) -f CMakeFiles/gtest.dir/build.make CMakeFiles/gtest.dir/tests/gtest-1.8.1/gtest-all.cc.o
.PHONY : tests/gtest-1.8.1/gtest-all.cc.o

tests/gtest-1.8.1/gtest-all.i: tests/gtest-1.8.1/gtest-all.cc.i

.PHONY : tests/gtest-1.8.1/gtest-all.i

# target to preprocess a source file
tests/gtest-1.8.1/gtest-all.cc.i:
	$(MAKE) -f CMakeFiles/gtest.dir/build.make CMakeFiles/gtest.dir/tests/gtest-1.8.1/gtest-all.cc.i
.PHONY : tests/gtest-1.8.1/gtest-all.cc.i

tests/gtest-1.8.1/gtest-all.s: tests/gtest-1.8.1/gtest-all.cc.s

.PHONY : tests/gtest-1.8.1/gtest-all.s

# target to generate assembly for a file
tests/gtest-1.8.1/gtest-all.cc.s:
	$(MAKE) -f CMakeFiles/gtest.dir/build.make CMakeFiles/gtest.dir/tests/gtest-1.8.1/gtest-all.cc.s
.PHONY : tests/gtest-1.8.1/gtest-all.cc.s

tests/gtest-1.8.1/gtest_main.o: tests/gtest-1.8.1/gtest_main.cc.o

.PHONY : tests/gtest-1.8.1/gtest_main.o

# target to build an object file
tests/gtest-1.8.1/gtest_main.cc.o:
	$(MAKE) -f CMakeFiles/gtest_main.dir/build.make CMakeFiles/gtest_main.dir/tests/gtest-1.8.1/gtest_main.cc.o
.PHONY : tests/gtest-1.8.1/gtest_main.cc.o

tests/gtest-1.8.1/gtest_main.i: tests/gtest-1.8.1/gtest_main.cc.i

.PHONY : tests/gtest-1.8.1/gtest_main.i

# target to preprocess a source file
tests/gtest-1.8.1/gtest_main.cc.i:
	$(MAKE) -f CMakeFiles/gtest_main.dir/build.make CMakeFiles/gtest_main.dir/tests/gtest-1.8.1/gtest_main.cc.i
.PHONY : tests/gtest-1.8.1/gtest_main.cc.i

tests/gtest-1.8.1/gtest_main.s: tests/gtest-1.8.1/gtest_main.cc.s

.PHONY : tests/gtest-1.8.1/gtest_main.s

# target to generate assembly for a file
tests/gtest-1.8.1/gtest_main.cc.s:
	$(MAKE) -f CMakeFiles/gtest_main.dir/build.make CMakeFiles/gtest_main.dir/tests/gtest-1.8.1/gtest_main.cc.s
.PHONY : tests/gtest-1.8.1/gtest_main.cc.s

tests/linear_map_tests.o: tests/linear_map_tests.cpp.o

.PHONY : tests/linear_map_tests.o

# target to build an object file
tests/linear_map_tests.cpp.o:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/tests/linear_map_tests.cpp.o
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/tests/linear_map_tests.cpp.o
.PHONY : tests/linear_map_tests.cpp.o

tests/linear_map_tests.i: tests/linear_map_tests.cpp.i

.PHONY : tests/linear_map_tests.i

# target to preprocess a source file
tests/linear_map_tests.cpp.i:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/tests/linear_map_tests.cpp.i
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/tests/linear_map_tests.cpp.i
.PHONY : tests/linear_map_tests.cpp.i

tests/linear_map_tests.s: tests/linear_map_tests.cpp.s

.PHONY : tests/linear_map_tests.s

# target to generate assembly for a file
tests/linear_map_tests.cpp.s:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/tests/linear_map_tests.cpp.s
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/tests/linear_map_tests.cpp.s
.PHONY : tests/linear_map_tests.cpp.s

tests/linear_set_tests.o: tests/linear_set_tests.cpp.o

.PHONY : tests/linear_set_tests.o

# target to build an object file
tests/linear_set_tests.cpp.o:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/tests/linear_set_tests.cpp.o
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/tests/linear_set_tests.cpp.o
.PHONY : tests/linear_set_tests.cpp.o

tests/linear_set_tests.i: tests/linear_set_tests.cpp.i

.PHONY : tests/linear_set_tests.i

# target to preprocess a source file
tests/linear_set_tests.cpp.i:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/tests/linear_set_tests.cpp.i
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/tests/linear_set_tests.cpp.i
.PHONY : tests/linear_set_tests.cpp.i

tests/linear_set_tests.s: tests/linear_set_tests.cpp.s

.PHONY : tests/linear_set_tests.s

# target to generate assembly for a file
tests/linear_set_tests.cpp.s:
	$(MAKE) -f CMakeFiles/correrTests.dir/build.make CMakeFiles/correrTests.dir/tests/linear_set_tests.cpp.s
	$(MAKE) -f CMakeFiles/correrTests-Wall.dir/build.make CMakeFiles/correrTests-Wall.dir/tests/linear_set_tests.cpp.s
.PHONY : tests/linear_set_tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... gtest_main"
	@echo "... edit_cache"
	@echo "... correrTests"
	@echo "... rebuild_cache"
	@echo "... gtest"
	@echo "... correrTests-Wall"
	@echo "... correrValgrind"
	@echo "... src/BaseDeDatos.o"
	@echo "... src/BaseDeDatos.i"
	@echo "... src/BaseDeDatos.s"
	@echo "... src/Consulta.o"
	@echo "... src/Consulta.i"
	@echo "... src/Consulta.s"
	@echo "... src/Driver.o"
	@echo "... src/Driver.i"
	@echo "... src/Driver.s"
	@echo "... src/Registro.o"
	@echo "... src/Registro.i"
	@echo "... src/Registro.s"
	@echo "... src/Table.o"
	@echo "... src/Table.i"
	@echo "... src/Table.s"
	@echo "... tests/driver_test.o"
	@echo "... tests/driver_test.i"
	@echo "... tests/driver_test.s"
	@echo "... tests/gtest-1.8.1/gtest-all.o"
	@echo "... tests/gtest-1.8.1/gtest-all.i"
	@echo "... tests/gtest-1.8.1/gtest-all.s"
	@echo "... tests/gtest-1.8.1/gtest_main.o"
	@echo "... tests/gtest-1.8.1/gtest_main.i"
	@echo "... tests/gtest-1.8.1/gtest_main.s"
	@echo "... tests/linear_map_tests.o"
	@echo "... tests/linear_map_tests.i"
	@echo "... tests/linear_map_tests.s"
	@echo "... tests/linear_set_tests.o"
	@echo "... tests/linear_set_tests.i"
	@echo "... tests/linear_set_tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

